#CODIGO USANDO FUNÇÃO DE TRANSFORMAÇÃO DE ESTRINGO TRANSFORMANDO CARACTERES ESPECIFICOS 
#DENTRO DE UMA VARIAVEL EM OUTRO CARACTERE CONTENDO A MESMA QUANTIDADE E CARACTERE E RETORNADO.  

nome="iderval jose de lima neto"
print(nome.replace('neto', 'show'))

